# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = '2048'
    vb.cpus = '2'
  end

  config.omnibus.chef_version = '12.9.41'

  config.vm.provision "shell", inline: <<-SHELL
    set -e

    if ! [ "$(dpkg -l |grep mysql-server)" ]
    then

      debconf-set-selections <<< 'mysql-server-5.6 mysql-server/root_password password root'
      debconf-set-selections <<< 'mysql-server-5.6 mysql-server/root_password_again password root'
      apt-get install -y --allow-unauthenticated apache2 unzip mysql-server-5.6 python2.7-dev
    fi

    if ! [ -d "/opt/master/Awesome-Appliance-Repair-master" ]
    then

      mkdir -p /opt/master
      cd /opt/master
      wget https://github.com/colincam/Awesome-Appliance-Repair/archive/master.zip
      unzip master.zip

      cd Awesome-Appliance-Repair-master
      mv AAR /var/www/
      chown -R www-data:www-data /var/www/AAR
      rm -f /etc/apache2/sites-enabled/*
    fi
  SHELL

  config.vm.provision 'chef_solo' do |chef|
    chef.add_recipe 'my-first-cookbook'
    chef.cookbooks_path = 'cookbooks'
  end

  #config.vm.provision 'shell', inline: <<-SHELL
  #  set -e
  #  cd /vagrant
  #  echo "root" | ./AARinstall.py
  #SHELL
end
