# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.provider "virtualbox" do |vb|
    vb.memory = '1024'
    vb.cpus = '2'
  end

  config.omnibus.chef_version = '12.9.41'

  config.vm.provision 'chef_solo' do |chef|
    chef.add_recipe 'my-first-cookbook'
    chef.cookbooks_path = 'cookbooks'
  end
end
